name: The ViKid Truth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42311
title: The ViKid Truth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f6ed4'
    - '#9bcefd'
    - '#000900'
    - '#ff9100'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
