layout_spectrum: 0.7298604
color:
  saturation: 0.4383148
  lightness: 0.5710228
  brandStrength: 0.8823845
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#303030'
    - '#5C5C5C'
    - '#9A9A9A'
  rhythmicContrast: 0.4226638
typography_spectrum: 0.7019334
name: The ViKid Truth
