name: The ViKid Truth
favicon: null
layout_spectrum: 0.7298604
typography_spectrum: 0.7019334
title: The ViKid Truth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#303030'
    - '#5C5C5C'
    - '#9A9A9A'
  brandStrength: 0.6875
  lightness: 0.1573576
  saturation: 0.6875
  rhythmicContrast: 0.5204082
purpose: []
